categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: " 📘 Documentation"
    labels:
      - "documentation"
template: |
  ## Changes

  $CHANGES
