categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: " 📘 Documentation"
    labels:
      - "documentation"
template: |
  ## Changes
  $CHANGES
  ---
  ### 👽 Contributors
  Our big thanks to:
  $CONTRIBUTORS
  ---
  ### 🏷️ Previous tag
  $PREVIOUS_TAG
