name: Packaging

on:
  push:
    tags:
      - "v*"

jobs:
  Packaging:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        name: Publish to GitHub Packages
        run: npm publish
