name: Packaging

on:
  push:
    tags:
      - "v*"
  create:
    tags:
      - "v*"

jobs:
  Packaging:
    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: npm install
        run: npm ci

      - name: npm build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build --if-present

      - name: Release
        uses: ridedott/release-me-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          node-module: true
          commit-assets: |
            ./dist
          release-assets: |
            ./generated/my-asset.tar.gz

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        name: Publish to GitHub Packages
        run: npm publish
